version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: payment_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: payment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - payment_network

networks:
  payment_network:
    driver: bridge

volumes:
  db_data:
